[package]
name = "backend-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0.145"
anyhow = "1.0.100"
